name: pyIndiaFactorInvesting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - notebook
  - ipykernel
  - pandas>=2,<3
  - numpy<2
  - matplotlib
  - scipy
  - statsmodels
  - pip
  - pip:
    - indiafactorlibrary
